project_id         = "terraform-demo-prod"
project_name       = "terraform-demo-prod"
app_name           = "terraform-demo"
public_subnet_cidr = "10.101.7.0/24"
region             = "us-central1"
env_name           = "prod"
