project_id         = "terraform-demo-dev"
project_name       = "terraform-demo-dev"
app_name           = "terraform-demo"
public_subnet_cidr = "10.101.0.0/24"
region             = "us-central1"
env_name           = "dev"
