name: Terraform deploy
on:
  - push

env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  terraform_version: 1.5.2

jobs:
  terraform-dev:
    runs-on: ubuntu-22.04
    environment: dev
    steps:
      - run: |
          echo "carlosrv999 estuvo aqui"
      - uses: actions/checkout@v3
        name: Checkout repo
      - uses: hashicorp/setup-terraform@v2
        name: Set Terraform version
        with:
          terraform_version: ${{ env.terraform_version }}
      - name: Get Terraform version
        run: |
          terraform -v
      - name: Terraform init
        run: |
          terraform init
      - name: Terraform Set Workspace Dev
        run: |
            terraform workspace select dev
      - name: Terraform plan
        run: |
          terraform plan -var-file=terraform.dev.tfvars -out tfplan
      - name: Terraform apply
        run: |
          terraform apply tfplan

  terraform-staging:
    needs: terraform-dev
    runs-on: ubuntu-22.04
    environment: staging
    steps:
      - run: |
          echo "carlosrv999 estuvo aqui"
      - uses: actions/checkout@v3
        name: Checkout repo
      - uses: hashicorp/setup-terraform@v2
        name: Set Terraform version
        with:
          terraform_version: ${{ env.terraform_version }}
      - name: Get Terraform version
        run: |
          terraform -v
      - name: Terraform init
        run: |
          terraform init
      - name: Terraform Set Workspace Staging
        run: |
            terraform workspace select staging
      - name: Terraform plan
        run: |
          terraform plan -var-file=terraform.staging.tfvars -out tfplan
      - name: Terraform apply
        run: |
          terraform apply tfplan

  terraform-prod:
    needs: [terraform-dev, terraform-staging]
    runs-on: ubuntu-22.04
    environment: prod
    steps:
      - run: |
          echo "carlosrv999 estuvo aqui"
      - uses: actions/checkout@v3
        name: Checkout repo
      - uses: hashicorp/setup-terraform@v2
        name: Set Terraform version
        with:
          terraform_version: ${{ env.terraform_version }}
      - name: Get Terraform version
        run: |
          terraform -v
      - name: Terraform init
        run: |
          terraform init
      - name: Terraform Set Workspace Production
        run: |
            terraform workspace select prod
      - name: Terraform plan
        run: |
          terraform plan -var-file=terraform.prod.tfvars -out tfplan
      - name: Terraform apply
        run: |
          terraform apply tfplan
