name: Terraform
on:
  - push

env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

jobs:
  terraform:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          echo "carlosrv999 estuvo aqui"
      - uses: actions/checkout@v3
        name: Checkout repo
      - uses: hashicorp/setup-terraform@v2
        name: Set Terraform version
        with:
          terraform_version: 1.5.2
      - name: Get Terraform version
        run: |
          terraform -v
      - name: Terraform init
        run: |
          terraform init
